apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: votting-app
    tier: redis
spec:
  containers:
    - name: redis
      image: redis:alpine
      ports:
        - containerPort: 6379