apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    app: votting-app
    tier: result-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 31001
  selector:
    tier: vote-result
    