apiVersion: v1
kind: Pod
metadata:
  name: result
  labels:
    app: votting-app
    tier: result-front
spec:
  containers:
    - name: result
      image: dockersamples/examplevotingapp_result
      ports:
        - containerPort: 80