apiVersion: v1
kind: Pod
metadata:
  name: vote
  labels:
    app: votting-app
    tier: vote-front
spec:
  containers:
    - name: vote
      image: dockersamples/examplevotingapp_vote
      ports:
        - containerPort: 80
          