apiVersion: v1
kind: Service
metadata:
  name: vote-service
  labels:
    app: votting-app
    tier: vote-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    tier: vote-front
    